coreweave/kubernetes-cloud

docs/resources/billing-and-charges.md
Update the pricing link in the documentation
=> Resources: Update pricing link

virtual-server/examples/terraform/README.md, virtual-server/examples/terraform/examples/module-use.tf, virtual-server/examples/terraform/main.tf, virtual-server/examples/terraform/outputs.tf, virtual-server/examples/terraform/variables.tf, virtual-server/examples/terraform/vdi.tf, virtual-server/examples/terraform/vs.tf
Provides an example for cloud users to:
- Deploy a virtual desktop through Terraform via module
- An example for consuming the Terraform module
Resolves https://github.com/coreweave/infra-pm/issues/84
=> VDI Example Terraform

online-inference/custom-basnet/basnet-inferenceservice.yaml, online-inference/custom-pytorch-aitextgen/aitextgen-inferenceservice.yaml, online-inference/custom-sentiment/sentiment-inferenceservice.yaml, online-inference/image-classifier/service/classifier-inferenceservice.yaml
Resolves https://github.com/coreweave/infra-pm/issues/91
=> Updates InferenceService examples to use regular node affinities.

virtual-server/examples/python/README.md, virtual-server/examples/python/kubevirtclient.py, virtual-server/examples/python/main.py, virtual-server/examples/python/vsclient.py
fix #35 
This PR adds a missing argument and adds an example with a manifest update.
=> fix(vs): Add missing param and update example

virtual-server/examples/go/go.mod, virtual-server/examples/go/go.sum, virtual-server/examples/go/main.go, virtual-server/examples/kubectl/README.md, virtual-server/examples/kubectl/virtual-server-block-pvc.yaml, virtual-server/examples/kubectl/virtual-server-direct-attach-lb.yaml, virtual-server/examples/kubectl/virtual-server-shared-pvc.yaml, virtual-server/examples/kubectl/virtual-server.yaml, virtual-server/examples/nodejs/main.js, virtual-server/examples/python/main.py
This PR updates examples for new VS features:
- cloud-init
- publicsshkey
https://github.com/coreweave/kubernetes-cloud/issues/24
All examples were tested
=> feat(vs): Add cloudinit and sshpublickey to kubectl, go, node.js, python

virtual-server/examples/go/main.go, virtual-server/examples/kubectl/virtual-server-block-pvc.yaml, virtual-server/examples/kubectl/virtual-server-direct-attach-lb.yaml, virtual-server/examples/kubectl/virtual-server-shared-pvc.yaml, virtual-server/examples/kubectl/virtual-server-windows-cpu-only.yaml, virtual-server/examples/kubectl/virtual-server-windows-internal-ip-only.yaml, virtual-server/examples/kubectl/virtual-server-windows.yaml, virtual-server/examples/kubectl/virtual-server.yaml, virtual-server/examples/nodejs/main.js, virtual-server/examples/python/main.py
This PR removes security risks by comment and/or remove the user and password from Virtual Server examples.
=> fix(vs): Remove username and password from examples

virtual-server/examples/kubectl/virtual-server-block-pvc.yaml
Fixes https://github.com/coreweave/infra-pm/issues/140
=> feat(vs): Use Cloudinit to mount block volume

finetuner-workflow/finetune-pvc.yaml, finetuner-workflow/finetune-workflow.yaml, finetuner-workflow/finetuner/Dockerfile, finetuner-workflow/finetuner/ds_config.json, finetuner-workflow/finetuner/finetuner.py, finetuner-workflow/finetuner/requirements.txt, finetuner-workflow/inference-role.yaml
Need a PVC, only thing required in PVC is a `{{dataset}}` directory with text files.
Example Invocation:
```
-p run_name=test-2-7b \
-p model=EleutherAI/gpt-neo-2.7B \
-p pvc=finetune-data
```
PVC layout (default PVC name of `finetune-data`)
```
|- {{dataset}} (text files going into finetune)
|- {{dataset}}-{{tokenizer}}-{{context}}.tokens (generated from dataset)
|- finetunes (resulting artifacts)
|  |- {{run_name}}
|    |- results-{{run_name}}
|       |- run_name-NNNN (checkpoints)
|       |- ...
|       |- final (final model artifact)
|- cache (huggingface artifact cache)
|- torch (torch build cache)
```
=> (feat) Add code, Argo workflow, and Docker image for finetuning on CoreWeave

getting-started/k8ctl_setup.ps1
Matches cluster version by default, adds switch to use latest binaries if desired
=> feat: Pin binary versions in Windows setup script

finetuner-workflow/finetune-workflow.yaml
Update `finetune-workflow.yaml` to ensure that `-sanitize` is always true, and update to version of `dataset_tokenizer` with sanitization support.
Actual code change is here:
https://github.com/wbrown/gpt_bpe/commit/a075bc9665d2edad55afda71b6a40cf234da0132
=> Basic Input Sanitization

finetuner-workflow/finetune-workflow.yaml
Turns out the golang's regexp newline matching was a bit different than the usual ...
Added test cases and found bugs in the sanitizer.
Actual code here:
https://github.com/wbrown/gpt_bpe/commit/b60025df3761d810bf244d2685e583a03ebdfbe6
=> Update tokenizer to fixed sanitize code.

virtual-server/examples/kubectl/README.md, virtual-server/examples/kubectl/virtual-server-highly-burstable-ip.yaml
We might want to create a specific documentation page under the Networking section at some point for the highly burstable IP ranges. I do believe this example covers the need for now however.
=> Highly burstable IP Virtual Server example

virtual-server/examples/go/README.md, virtual-server/examples/go/main.go
The go example for VS makes floating service an option.
Additionally, it upgrades the os image and fixes a few prints.
=> fix(vs-go): Make floating service as option

online-inference/stable-diffusion/README.md, online-inference/stable-diffusion/service/service.py
* Fix link to CoreWeave docs
* Use `autocast` during image generation.
=> Stable Diffusion Updates

finetuner-workflow/finetuner/finetuner.py
previously was string always evaled as true in finetune.py
=> fixed typecasting for no_resume param allowing

docs/compass/examples/triton-inference-server-fastertransformer.md, online-inference/fastertransformer/download-weights-job-gpt-neox.yml
Solving the issue found here: #98
=> fixing fastertransformer example

online-inference/fastertransformer/client/sample_request.json, online-inference/fastertransformer/download-weights-job-gpt-neox.yml, online-inference/fastertransformer/download-weights-job-gptj.yml
Updating random_seed to UNIT64 for better inference quality.
=> chore(random_seed_update): UINT64 random seed

online-inference/fastertransformer/client/example.py, online-inference/fastertransformer/ft-inference-service-gptj.yml, online-inference/fastertransformer/ft-inference-service-neox.yml
This PR includes a client example to use GRPC. The code has been tested on HTTP/GRPC FT Inference Services. This will be followed up by a PR in #documentation to reflect the GRPC addition
=> feat(grpc): GRPC Streaming Client Example for Fastertransformer

argo-workflow/README.md
Argo Workflows changed their primary link - this updates it.
=> Update Argo Workflows link

virtual-server/examples/curl/run.sh, virtual-server/examples/curl/virtual-server.json, virtual-server/examples/go/main.go, virtual-server/examples/nodejs/main.js, virtual-server/examples/nodejs/package-lock.json, virtual-server/examples/python/kubevirtclient.py, virtual-server/examples/python/main.py
The PR upgrade examples for Virtual Server.
All examples were tested.
@microcosem I don't think we need to update anything in the doc but just let you know I'm updating the examples.
=> feat(vso): Update examples

online-inference/stable-diffusion/02-model-download-job.yaml, online-inference/stable-diffusion/02-optional-serialize-job.yaml, online-inference/stable-diffusion/03-inference-service.yaml, online-inference/stable-diffusion/03-optional-s3-upload-job.yaml
This replaces the placeholder images for the:
- [Inference Service](https://github.com/coreweave/ml-containers/pkgs/container/ml-containers%2Fsd-inference)
- [Serializer Job](https://github.com/coreweave/ml-containers/pkgs/container/ml-containers%2Fsd-serializer)
- [Model Downloader](https://github.com/wbrown/gpt_bpe/pkgs/container/gpt_bpe%2Fmodel_downloader)
=> Replace placeholder images for SD inference example

online-inference/fastertransformer/download-weights-job-gpt-neox.yml, online-inference/fastertransformer/model-storage-pvc.yml
This fixes https://github.com/coreweave/kubernetes-cloud/issues/148
=> feat(bug): Fixing Issue #148

tensorflow-jupyter/jupyter-pvc.yaml, tensorflow-jupyter/tensorflow-deployment.yaml
Changes submitted by Eta. Thanks!
Relates to coreweave/docs#123
[See Slack for further context](https://coreweave.slack.com/archives/C03L3KJ7708/p1679627730034709?thread_ts=1679005771.812899&cid=C03L3KJ7708).
=> Update TensorFlow deployment

online-inference/stable-diffusion/Dockerfile, online-inference/stable-diffusion/Dockerfile.serializer, online-inference/stable-diffusion/serializer/requirements.txt, online-inference/stable-diffusion/serializer/serialize.py, online-inference/stable-diffusion/service/requirements.txt, online-inference/stable-diffusion/service/service.py, sd-dreambooth-workflow/db-finetune-pvc.yaml, sd-dreambooth-workflow/db-workflow-event-binding.yaml, sd-dreambooth-workflow/db-workflow-template.yaml, sd-dreambooth-workflow/db-workflow.yaml, sd-dreambooth-workflow/huggingface-secret.yaml, sd-dreambooth-workflow/inference-role.yaml, sd-dreambooth-workflow/wanbd-secret.yaml, sd-finetuner-workflow/huggingface-secret.yaml, sd-finetuner-workflow/sd-finetune-workflow-event-binding.yaml, sd-finetuner-workflow/sd-finetune-workflow-template.yaml, sd-finetuner-workflow/sd-finetune-workflow.yaml, sd-finetuner-workflow/sd-finetuner/Dockerfile, sd-finetuner-workflow/sd-finetuner/datasets.py, sd-finetuner-workflow/sd-finetuner/finetuner.py, sd-finetuner-workflow/sd-finetuner/requirements.txt, sd-finetuner-workflow/wanbd-secret.yaml
This PR adds support for the [Dreambooth method](https://dreambooth.github.io/) in the stable diffusion finetuner. It also adds an example Argo workflow that does Dreambooth finetuning and creates an inference service with the finetuned model.
Inspired by [huggingface's dreambooth training script](https://github.com/huggingface/diffusers/tree/main/examples/dreambooth).
**Dreambooth TLDR**
The point of dreambooth finetuning is to teach the model the meaning of a specific object/face with little training data. The same prompt will be used for all instance images and it will contain "unique text" that will be used to describe the new object. Once finetuned, you can use the unique text to generate images with your specific object/face. For example, given 5 pictures of your dog, you can use …
=> feat(dreambooth): Add dreambooth to sd finetuner

online-inference/stable-diffusion/README.md
The documentation link in the readme is broken, this PR fixes that.
=> Fix broken URL in readme.

online-inference/tensorizer-isvc/benchmark/load_test_async.py, online-inference/tensorizer-isvc/benchmark/load_test_sync.py, online-inference/tensorizer-isvc/gptj_6b_hf/flask/transformer_flask.py, online-inference/tensorizer-isvc/gptj_6b_hf/kserve/transformer_kserve.py, online-inference/tensorizer-isvc/gptj_6b_tensorizer/flask/tensorizer_flask.py, online-inference/tensorizer-isvc/gptj_6b_tensorizer/kserve/tensorizer_kserve.py
Tweaks and code improvements for #204; mostly formatting and improvements to the benchmarks.
Highlights:
- Code formatted, imports sorted, unused imports removed
- Async benchmark code has been simplified a bit
- Added `--verbose` and `--quiet` command line flags to control the logging in those benchmarks a bit more
- The sync benchmarks
I'd like to add a few more improvements before merging this, but wanted the progress here to be visible in a PR at least so that the work doesn't get duplicated.
=> Tensorizer ISVC Example Improvements

online-inference/stable-diffusion/02-model-download-job.yaml
ghcr.io/wbrown/gpt_bpe/model_downloader:1fe59a1
=> (fix) update model downloader public image URL
