argo-workflow/argo-install.yaml

To upgrade Argo Workflow to the latest version `3.0.0`
This PR is a draft until the final `3.0.0` is released.
This PR allows testing recent release candidates.
- `3.0.2`: https://github.com/argoproj/argo-workflows/releases/tag/v3.0.2
- `3.0.1`: https://github.com/argoproj/argo-workflows/releases/tag/v3.0.1
- `3.0.0`: https://github.com/argoproj/argo-workflows/releases/tag/v3.0.0
- `3.0.0-rc9`: https://github.com/argoproj/argo-workflows/releases/tag/v3.0.0-rc9
- `3.0.0-rc8`: https://github.com/argoproj/argo-workflows/releases/tag/v3.0.0-rc8
- `3.0.0-rc6`: https://github.com/argoproj/argo-workflows/releases/tag/v3.0.0-rc6
- `3.0.0-rc5`: https://github.com/argoproj/argo-workflows/releases/tag/v3.0.0-rc5
- `3.0.0-rc4`: https://github.com/argoproj/argo-workflows/releases/tag/v3.0.0-rc4
- …

feat(argo-workflow): Upgrade to 3.0.0

---

getting-started/k8ctl_setup.ps1

This PR adds `k8ctl_setup.ps1`, a PowerShell script that does the following:
- Downloads latest kubectl binary for Windows
- Downloads latest virtctl binary for Windows
- Adds above variables to system PATH
- Adds alias for `k` and `virt`
- Adds cw-kubeconfig to appropriate location
Script is interactive, or can be ran silently with `-Silent` switch. Prompts for an Administrative context if necessary. 
Designed to be executed in a one-liner, E.G: `& $([scriptblock]::Create((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/coreweave/kubernetes-cloud/master/getting-started/k8ctl_setup.ps1')))`
This allows us to create documentation for our Windows users ensuring they are using a consistent environment for `kubectl`.

feat(docs) Add Windows kubectl/virtctl setup script

---

virtual-server/examples/kubectl/virtual-server-static-mac.yaml

This PR adds an example with a static mac address.
The mac address in VS is `A2-1F-EE-09-06-5D` and the same in VMI:
```
john@example-vs-static-mac:~$ ifconfig
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
inet 192.168.99.1  netmask 255.255.255.0  broadcast 192.168.99.255
ether 02:42:0c:34:e8:11  txqueuelen 0  (Ethernet)
RX packets 0  bytes 0 (0.0 B)
RX errors 0  dropped 0  overruns 0  frame 0
TX packets 0  bytes 0 (0.0 B)
TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
enp1s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet 10.146.48.242  netmask 255.255.255.255  broadcast 0.0.0.0
inet6 fe80::a01f:eeff:fe09:65d  prefixlen 64  scopeid 0x20<link>
ether a2:1f:ee:09:06:5d  txqueuelen 1000  (Ethernet)
RX packets 50700  bytes 189790729 (189.7 MB)
RX errors 0 …
```

feat(vso): Add static mac address example cli

---

finetuner-workflow/finetune-workflow.yaml
finetuner-workflow/finetuner/finetuner.py

* Allow `context` size to be passed to the finetuner to match the tokenizer context size.
* Fix cases where the `finetunes` directory does not yet exist before trying to `chdir` to it.

Pass in Context Size to `finetune.py` and fix missing `finetunes` dir

---

docs/workflows/argo.md

Just noticed this URL either changed (and broke this link), or a word was accidentally missed!

Fix broken link to Argo Workflows.

---

virtual-server/pvc-clone.sh

This PR adds a case for identifying PVC for a VirtualServer VMI as well as a Helm VMI.
This is needed due to the difference in spec: 
`k get vmi -o json`
Helm VMI:
```
"volumes": [
{
"name": "dv",
"persistentVolumeClaim": {
"claimName": "vs-windows10"
}
}, 
```
VS VMI:
```
"volumes": [
{
"dataVolume": {
"name": "vs-windows10"
},
"name": "root"
},
```

fix(docs) Add VirtualServer VMI case to pvc-clone.sh

---

virtual-server/examples/kubectl/virtual-server-block-pvc.yaml
virtual-server/examples/kubectl/virtual-server-ephemeral-disk.yaml
virtual-server/examples/kubectl/virtual-server-shared-pvc.yaml

This PR adds an example with the ephemeral disk.
The disk is automatically formatted and mounted to `/mnt/vdb` via `cloud-init` script.
Additionally, I updated old root sources.
fix https://github.com/coreweave/virtual-server-operator/issues/48

feat(vso): Add ephemeral disk example

---

virtual-server/examples/python/vsclient.py

In some cases, event object does not have `status`, handled this in Python `vsclient` ready function.

Fix unhandled condition in Python vsclient ready function

---

online-inference/stable-diffusion/service/service.py

Update diffusers usage in `service.py` to avoid a `KeyError: 'sample'` error when getting the result from the pipeline.  
```
[E 230101 03:53:23 web:1798] Uncaught exception POST /v1/models/stable-diffusion-v1-4:predict (127.0.0.1)
HTTPServerRequest(protocol='http', host='[snip]', method='POST', uri='/v1/models/stable-diffusion-v1-4:predict', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1713, in _execute
result = await result
File "/usr/local/lib/python3.8/dist-packages/kserve/handlers/predict.py", line 70, in post
response = await model(body)
File "/usr/local/lib/python3.8/dist-packages/kserve/model.py", line 87, in __call__
else self.predict(request)
File "/app/service.py", line 118, in …
```

Fix diffusers usage error in SD inference example

---

finetuner-workflow/finetune-workflow.yaml

Fixes the default tokenizer in `finetuner-workflow/finetune-workflow.yaml`. It was previously receiving an uninterpolated string literal.
Also updates the default model parameter with its new Hugging Face name.

Fix default tokenizer path.

---

finetuner-workflow/finetune-workflow.yaml

Corrects propagation of an empty `prompt_file` workflow parameter in `finetuner-workflow/finetune-workflow.yaml` to its `finetuner.py` script to perform model training without sampling.

Fix default prompt file.

---

online-inference/stable-diffusion/service/requirements.txt
sd-finetuner-workflow/sd-finetune-workflow.yaml

- Use bool's instead of strings for 'skip step' parameters
- Give write permissions for the nonroot model downloader user
- Update transformers version for the sd finetuning image
This fix comes from investigating [a freshdesk ticket](https://coreweave.freshdesk.com/a/tickets/5740) from a client saying that the sd-finetuner doc page wasn't working properly for them.
After stepping through the docs myself, what I believe happened is the model-downloader didn't download the model bc the nonroot user didn't have the necessary permissions. The model downloader didn't throw an error so the finetuner started. The finetuner also finished successfully right away but if you look at the logs the subprocess threw an error as expected. Looking at the [accelerate source …

fix: Various sd-finetuner fixes

---

finetuner-workflow/finetuner/ds_config.json
finetuner-workflow/finetuner/finetuner.py

All training configurations _except for training a model in mixed precision mode ("fp16") with DeepSpeed enabled_ were broken, because the tokenized dataset loader was outputting its accompanying attention masks as all zeroes, meaning "ignore all training data."
[A bug fixed](https://github.com/huggingface/transformers/pull/17306) in version 4.21.0 of the transformers library had allowed models with sufficiently extreme parameters to ignore the attention mask, which was the only way this code was previously able to function. Updating that dependency revealed this bug.
DeepSpeed's mixed precision mode seemingly reintroduced the bug that had previously allowed this code to function, which let it continue to sort of work under select circumstances even with the updated transformers library. …

Fix finetuner attention masking.

---

finetuner-workflow/finetune-workflow.yaml

Updating model-downloader image for the finetuner-workflow from 7ffb3ec to  e2ef65f 
this update allows the model-downloader to support the new metadata version from hugging face, where the merges.txt and vocab.json is included in the tokenizer.json as a key in the json.

Update Model-downloader image

---

finetuner-workflow/finetuner/Dockerfile
finetuner-workflow/finetuner/evaluator.py
finetuner-workflow/finetuner/finetuner.py
finetuner-workflow/finetuner/requirements.txt
finetuner-workflow/finetuner/utils.py

This PR contains some fixes, improvements, and refactoring to polish off the LLM finetuner update (#128).
When the `no_shuffle` flag was enabled, the finetuner did not correctly respect the train/eval ratio.
It would always use 100% of the dataset for training, and overlap that with the (shuffled, ironically) eval dataset, even though those shouldn't be mixed. This PR changes the implementation to extract a contiguous block (placed randomly) for the eval dataset, and to use the rest of the dataset minus that particular section for the train dataset, all while preserving the original order.
DeepSpeed logging is now re-enabled whenever the `--log-level` command line argument to the finetuner is set to `DEBUG`, for maximal information.
Several of the listed (and even imported) dependencies …

LLM Finetuner Update Polish

---

finetuner-workflow/finetune-workflow.yaml
finetuner-workflow/finetuner/evaluator.py
finetuner-workflow/finetuner/finetuner.py
finetuner-workflow/finetuner/requirements.txt

- f23b16dbac077b2134f849a3ab36a3a67b0803d7: Fixed `PerformanceCallback` accidentally being disabled when no `--prompt_file` is given.
- 2f677311320502677f4c6b74ec8c0e98523aa993: Replaced manual GPU-counting with DeepSpeed's world size when calculating the number of contexts trained.
- e37b7d01dd93df1e862b0039dfd671627a23226d: Temporarily disabled `train_ratio` as a workflow parameter.
- It isn't implemented correctly as-is, and simply discards training data with no benefit.
- For now, `finetuner.py` emits a warning if it is passed a `--train_ratio` other than `1.0`, and overrides it to `1.0`.
- 9a06e683cb7731b3767d97f485d673692851521f: Stopped masking end-of-sentence tokens as padding if the finetuner can't tell the two apart.
- This was preventing the finetuner from learning the EOS …

More finetuner update fixes.

---

spark/cpu-pod-template.yaml
spark/docker/Dockerfile
spark/docker/download_imgdataset.py
spark/docker/requirements.txt
spark/example-spark-submit.sh
spark/jupyter/interactive-example.ipynb
spark/jupyter/jupyter-service.yaml
spark/spark-pvc.yaml
spark/spark-role.yaml
spark/wanbd-secret.yaml

https://github.com/coreweave/docs/issues/228
This PR adds examples of running Spark on Kubernetes. Both of the examples use [img2dataset](https://github.com/rom1504/img2dataset).
The first example runs the spark job in "cluster" mode, and creates the job using `spark-submit`. This is the "simple" example and downloads a small dataset with 1 executor.
The second example involves deploying a service running Jupyter Lab. Then the spark job can be run from within a notebook in client mode. This example uses dynamic executors to scale up and down based on the current jobs, and will use 5 executors to download CC12M in ~1 hour. It includes logging to Weights and Biases.
This PR will stay as a draft until the docs are ready.
TODO Before merge:

feat(spark): Add a spark example

---

finetuner-workflow/finetune-role.yaml
finetuner-workflow/finetune-workflow.yaml

`alpine:3.12` apparently did not have CURL installed, replacing with `alpine/curl:3.14` and using an absolute path to the CURL binary fixes this issue where CURL is not found.

CURL fixes for GPT finetuner

---

finetuner-workflow/finetuner/finetuner.py
finetuner-workflow/finetuner/utils.py

More fixes and improvements for #128.
- 38c5e7e75438c0506f7165176f7497ec7f393b54: Removed the unused `find_free_port` function, since it can't be used with the DeepSpeed launcher.
- f40f0b908b458e4cd7209b6bf72a139fa36c710f: Reorganized `TrainingArguments` constructor arguments and some minor improvements in setting `do_train`, `model.train()`, commenting out unused arguments, etc.
- 1f8e06df01723ed8e852411fb4989c9e850dd3e3: Set the finetuner's seed in the `TrainingArguments` constructor so it will actually be used during finetuning, and not be overwritten.
- 7d7438afa1bf52ce9c40a476425691cf596901dd: Changed initialization of the empty model for the tensorizer loading code to use `AutoModelForCausalLM.from_config()` instead of `AutoModelForCausalLM.from_pretrained()`
- …

Finetuner fixes: Random seeding, better empty model loading, more code cleanup

---

finetuner-workflow/finetune-workflow.yaml
finetuner-workflow/finetuner/Dockerfile
finetuner-workflow/finetuner/inference.py
finetuner-workflow/finetuner/requirements.txt

The previous GPT inference server used in the finetuning example was out of date to the point that it cannot run inference on Pythia or GPT-NeoX models. The changes in this PR also incorporates an inference server with the finetuner image itself for simplicity.
Sidenote, #198 was made out of accident due to me being a little sleep deprived :sweat_smile:

Updated Inference Server for GPT Finetuner

---

finetuner-workflow/finetune-workflow.yaml
finetuner-workflow/finetuner/inference.py

Implementing the fixes and tweaks I suggested for finetuner inference in #203.
- Ongoing inference no longer blocks the HTTP server's event loop
- Command line arguments instead of environment variables
- Extra: IP address can now be specified as a command line argument
- Extra: Inference on CPU (device ID -1) is fixed by not casting the model to fp16 on CPU
- ~~Renamed the container from `kfserving-container` to `http-inference-container`~~
- Reverted for compatibility with the Kubernetes-level `kfserving` integration

Finetuner inference tweaks

---

online-inference/tensorizer-isvc/gptj_6b_hf/flask/Dockerfile
online-inference/tensorizer-isvc/gptj_6b_hf/flask/requirements.txt
online-inference/tensorizer-isvc/gptj_6b_tensorizer/flask/Dockerfile
online-inference/tensorizer-isvc/gptj_6b_tensorizer/flask/requirements.txt

Proposed change to the Flask server setups in #204 for `tensorizer-isvc`.
Production deployments usually run Flask through `gunicorn` rather than Flask's embedded webserver for better performance. Setup for it is fairly trivial (adding `gunicorn` as a dependency and launching via `gunicorn` or `python -m gunicorn`), so since the deployed server in this example is expected to be benchmarked, this PR simply switches the Flask `InferenceService`s' Dockerfiles to launch through `gunicorn` instead.

perf(tensorizer-isvc): Use `gunicorn` as a WSGI server with Flask

---

finetuner-workflow/finetune-workflow.yaml
finetuner-workflow/finetuner/finetuner.py

This PR adds a new argument to #128 which allows clients to adjust the ratio of warm up steps to training steps which is fairly important since the GPT finetuner uses an adaptive optimizer (Adam), plus this also addresses @Eta0's feedback on a duplicate workflow argument.

feat(finetuner): add adjustable warmup

---

finetuner-workflow/finetune-workflow.yaml

This PR is meant to be merged into https://github.com/coreweave/kubernetes-cloud/pull/128 and addresses https://github.com/coreweave/kubernetes-cloud/issues/170 where training crashes when 8 GPUs are allocated but training works just fine with 7 GPUs. So it seems that the training pod was crashing previously due to exhausting shared memory.
This was fixed by creating a shared memory device and currently there is not a specified size limit for it.

Prevent crashing when using 8 GPUs due to shared memory exhaustion.

---

finetuner-workflow/finetuner/finetuner.py

Fix for #128 correcting a variable name typo when setting the `warmup_ratio` parameter that I didn't catch in #217.
- When setting the warmup steps as a ratio in `TrainingArguments`, the parameter name is `warmup_ratio`. It was accidentally left as `warmup_steps`, which is another valid parameter, but which behaves differently.

fix(finetuner): Use correct parameter name when setting `warmup_ratio`

---

sd-dreambooth-workflow/wanbd-secret.yaml

Typo in file name: "wanbd-secret.yaml" changed to "wandb-secret.yaml" in path: `/kubernetes-cloud/sd-dreambooth-workflow`.

fix(sd-dreambooth-workflow):correct file name typo wandb

---

cuda-ssh/sshd-data-pvc.yaml
cuda-ssh/sshd-deployment.yaml
cuda-ssh/sshd-root-pvc.yaml

This PR brings the deployment for the [`cuda-ssh` docs example](https://docs.coreweave.com/coreweave-kubernetes/examples/cuda-ssh) up to date.
The CUDA SSH container has been re-homed from:
- [docker.io/atlanticcrypto/cuda-ssh-server](https://hub.docker.com/r/atlanticcrypto/cuda-ssh-server)
To:
- [ghcr.io/coreweave/ml-containers/cuda-ssh](https://github.com/coreweave/ml-containers/pkgs/container/ml-containers%2Fcuda-ssh)
With the new container based on the NCCL version of [ghcr.io/coreweave/ml-containers/torch](https://github.com/coreweave/ml-containers/pkgs/container/ml-containers%2Ftorch). There is an alternative version of the container built off of the [torch image](https://github.com/coreweave/ml-containers/pkgs/container/ml-containers%2Ftorch)'s base edition that could also be used. …

Update CUDA SSH Example

---

online-inference/dalle-mini/01-model-download-job.yaml
online-inference/dalle-mini/02-inference-service.yaml
online-inference/dalle-mini/Dockerfile

pulling in changes from https://github.com/coreweave/kubernetes-cloud/pull/246 and also fixing the dall-e mega/dall-e mini inconsistencies so that all references point to dall-e mini.

(fix)bump nvidia cuda version and fix mega mini inconsistencies

---

online-inference/hf-llm/.dockerignore
online-inference/hf-llm/00-optional-s3-secret.yaml
online-inference/hf-llm/01-optional-s3-serialize-job.yaml
online-inference/hf-llm/02-inference-service.yaml
online-inference/hf-llm/serializer/serialize.py
online-inference/hf-llm/service/service.py

Fixes and polish for #303.
The `load_model_s3` code in `service/service.py` was somewhat brittle on account of parsing the `path_uri` name for a slash-separated HuggingFace ID. It failed when attempting to follow the default example of serializing and deserializing `distilgpt2` because it is an example of a single-component HuggingFace ID with no slashes: it picks up the bucket name as the first component and then breaks (for example: `s3://my-bucket/distilgpt2` picks up `hf_id == my-bucket/distilgpt2`). It also broke for other models if you add a trailing slash to the ID, or if you included the `/model.tensors` or `/fp16/model.tensors` segments, and so on.
This change switches it to use more robust regex parsing that normalizes all of these cases, e.g.:
- ✔️ …

HF LLM Inference: Fixes & style
